export const SAVE_SESSION = 'ADD_BOOKMARK';
export const SAVE_SESSION_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const SAVE_SESSION_ERROR = 'ADD_BOOKMARK_ERROR';

export const LOGIN_VIA_GOOGLE = 'LOGIN_VIA_GOOGLE';
export const LOGIN_VIA_GOOGLE_SUCCESS = 'LOGIN_VIA_GOOGLE_SUCCESS';
export const LOGIN_VIA_GOOGLE_ERROR = 'LOGIN_VIA_GOOGLE_ERROR';
